version: '3.9'
services:
  node:
    container_name: library_app
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/node
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - postgres
  postgres:
    container_name: library_postgres
    env_file:
      - .env
    build: ./src/database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  app:
  postgres:
