version: '3.9'
services:
  node:
    container_name: library_app
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - postgres
  postgres:
    container_name: library_postgres
    env_file:
      - .env
    build: ./src/database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
